### ISSUE TITLE
please include LICENSE files in published enumflags2_derive crates

### ISSUE THREAD

**Issue by decathorpe** [meithecatte/enumflags2#45]
Both the MIT and Apache-2.0 licenses require that redistributed sources contain a copy of the license terms. The lack of license text is technically a violation of the terms, which is a problem for both crates.io and Linux Distributions which redistribute this crate.

It looks like this was previously discussed in https://github.com/meithecatte/enumflags2/issues/27 but got reverted again?

**Comment by meithecatte** [comment]
The LICENSE files are included in the relevant directory in the repository. Can you provide specific steps to reproduce this issue?

**Comment by decathorpe** [comment]
You are correct. I think I accidentally browsed the files of some old repository state by accident -  the files are indeed still there. Sorry about the noise. 🤦🏼‍♂️
