### ISSUE TITLE
`set` API on `BitFlags` for conditional `insert`/`remove`

### ISSUE THREAD

**Issue by m4dh0rs3** [meithecatte/enumflags2#49]
The [bitflags](https://docs.rs/bitflags/latest/bitflags/trait.Flags.html#method.set) crate implements this method:

```rust
/// Call [`Flags::insert`] when `value` is `true` or [`Flags::remove`] when `value` is `false`.
fn set(&mut self, other: Self, value: bool)
where
    Self: Sized,
{
    if value {
        self.insert(other);
    } else {
        self.remove(other);
    }
}
```

It allows setting a specific flag(set) conditionally, which is common for [status registers](http://6502.org/users/obelisk/6502/reference.html#LDA).

**Comment by meithecatte** [comment]
Implemented in #50 – thanks! I'll see if I have any energy to get anything else into the next release. If this sits on `master` for a few days with no movement, feel free to ping me.
