### ISSUE TITLE
Add `from_bits` and `from_bits_truncate` to `BitFlag` trait

### ISSUE THREAD

**Issue by ronnodas** [meithecatte/enumflags2#52]
This would add the same convenience of `BitFlag::empty()` and `BitFlag::all()`, namely the inner enum type would be directly visible at the call site, and possibly avoid some type hints.

**Comment by meithecatte** [comment]
Oh, yeah, this makes sense. One thing to consider is that, if someone already has `from_bits` implemented on their type, this will technically be a breaking change. I'm not sure if that qualifies for a semver bump, though...

Also, there's `from_bits_unchecked`. I suppose it could make sense to do that as well?
