### ISSUE TITLE
Code mismatch between version on crates.io and tagged version in repo for v0.7.9

### ISSUE THREAD

**Issue by VorpalBlade** [meithecatte/enumflags2#57]
Using cargo-goggles I discovered that enumflags2 has differences between the version on crates.io and the version in the repo at the tag v0.7.9:

* lib.rs has additional documentation comments in the published version

The changes don't seem malicious (and I would assume this is an honest mistake with placing the tag at the wrong commit), but they are somewhat concerning given the recent xz backdoor. I would like an explanation of what is going on here.

**Comment by meithecatte** [comment]
Ah, looks like `git push` without `--tags` doesn't actually push the tag changes? I think what happened is that I decided to fix one last issue when I was preparing to write the release notes, and I didn't properly move the tag. Thanks for checking, I moved the tag to the proper commit.
